### ISSUE TITLE
No file on disk

### ISSUE THREAD

**Issue by Arthedian** [sigurdga/django-dropzone-upload#1] opened 2014-01-15 18:13 UTC
When i upload file through localhost, it doesnt save anything to disk. Why? Or where it is saved?

**Comment by metakermit** [comment] 2014-07-11 23:00
Yes, I also noticed this. It seems to me that the problem is that the form is never submitted. So the file is HTTP posted, but the form is never submitted to trigger Django's response to store it to 'pictures/'. I managed to hack it by adding `<input type="submit" id="submit-all" />` into the form and following [this tutorial](http://amatellanes.wordpress.com/2013/11/05/dropzonejs-django-how-to-build-a-file-upload-form/), but I still didn't get quite what I want - a simple drag'n'drop way of uploading files onto the server.

**Comment by sigurdga** [comment] 2014-07-12 00:22
I have found the problem, and fixed it in 7ad1d9afdbf8db2960ac6b402f4da3f1675cc86f. It was form field name that did not match the field of the database. I'm not sure how this may have worked before – probably temprarily between my commits.

The form is submitted by the dropzone library, as an ajax post. Django backend is receiving it, but there is no easy way to tell what is going wrong, since I wanted this example to be minimal. I had  to (temporarily) add an form_invalid() in the view to see what happend when form validation failed (not committed, as it was just debugging prints to display form.errors).

**Closed as completed by sigurdga** 2014-07-12 00:22 UTC

**Comment by metakermit** [comment] 2014-07-12 08:34
Ah, OK it works now. But there's also another thing I didn't notice initially - the file must be a picture. I didn't catch that from the README. If I just drop a .txt file, it will add the preview icon, but it won't actually upload it. Maybe that's because `Picture.file` is an `ImageField`, so anything other than an image results in an invalid form.

**Comment by sigurdga** [comment] 2014-07-12 20:51
You are right. I have just updated the Readme to mention using ImageField. Changing to FileField should be fairly easy, as I don't thing there is a restriction set on just uploading files in the Dropzone configuration used (there is an option for restriction to image files, but this project is only using default configuration).
